### ISSUE TITLE
Using `rad-dropdown` with a `rad-state` has issues getting closed using the `rad-state`'s `close` method

### ISSUE THREAD

**Issue by alleman** [healthsparq/ember-radical#75]
```
<section class="new-drawer-section">
  {{#rad-state as |state stateActions|}}
    {{#rad-drawer externalToggle=state Target='Click me' as |components hidden|}}
      {{#components.content}}
        {{#rad-button click=stateActions.close}}Button{{/rad-button}}  
        {{#rad-button click=(action stateActions.close)}}Button 2{{/rad-button}}
      {{/components.content}}
    {{/rad-drawer}}
  {{/rad-state}}
</section>`

```
One of the buttons inside the content should close the dropdown, but it doesn't.

**Comment by evrowe** [comment]
Upon review, this isn't so much a bug as it is just an issue with how booleans and the `stateActions` actions manipulate the value of `state`. Always using `stateActions.toggleState` will overcome this problem, OR inverting the value of state when passed into `rad-drawer` will also work (e.g. `externalToggle=(not state)`.

There are some changes we can make to `rad-drawer` and `rad-state` to make this a little easier to grok, though.

For starters, we should deprecate the `externalToggle` prop of `rad-drawer` and have people pass `hidden` instead, since `externalToggle` is just a proxy for the internal `hidden` prop.

Secondly, the actions on `rad-state` need to be renamed for clarity; right now they are named `open` and `close`, which is presumptive. Those action names should be deprecated and updated with more explicit names like `setTrue` and `setFalse` so it is more obvious how the value of `state` is being manipulated.
